name: Build firmware

on:
  push:
    branches: [ "*" ]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 20
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y sdcc build-essential python2
    - name: Build
      run: |
        make -C Firmware/ all install
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          Firmware/dst/*
